name: Update Tamagotchi

on:
  schedule:
    - cron: "0 * * * *"   # every hour
  workflow_dispatch:      # manual run

jobs:
  update-svg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install deps
        run: pip install requests
      - name: Update SVG
        run: python update_svg.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit and push
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add tamagotchi.svg
          git commit -m "Update Tamagotchi SVG"
          git push
